### ISSUE TITLE
[Firefox & Synology] Refreshing after catching NZB

### ISSUE THREAD

**Issue by Stimmenhotel** [Tensai75/NZBDonkey#5] opened 2019-08-15 21:07 UTC
Hey there, I have another weird behavior to report.
I am using Firefox and have my Synology linked with the donkey.
If I have a Tab open with my NAS, this Tab gets refreshed after the donkey made his work on another tab.
Quite annoying if I am working on the NAS at that moment, while searching on another tab.
Once I use the nas-website on another browser (chrome) and firefox for searching, everything works fine, no refreshing etc.

Could you take a look into this problem?

**Comment by Tensai75** [comment] 2019-08-25 09:54
Thanks for pointig this out.
I was able to reproduce this bug and it is due to the authorisation routine for the Diskstation API which is setting a cookie interfering with the cookie set by the Diskstation web interface what causes the Diskstation web interface to reload.
Will be fixed in the next version.

**Comment by Tensai75** [comment] 2019-10-26 05:33
Resolved with v.0.7.2

**Closed as completed by Tensai75** 2019-10-26 05:33 UTC
Labels: bug
